- name: download latest agent keeperx
  get_url:
    url: "{{ debian_url_agent_keeperx }}"
    dest: /tmp/debian/keeperx.deb

- name: Installing the Hive Agent on debian-based Linux endpoints
  shell:
    cmd: sudo RQTPARAMS="https://{{ validate_server_url }} â€“gids {{ validate_group_IDs }}" dpkg -i /tmp/debian/keeperx.deb
